### PR TITLE
Added maze generator and added python3 support

### PR DESCRIPTION
**Pull request by JonnoFTW**
Added a maze generator, use it like:

```
python mazerunner/generator.py output.txt 33 43
```

To generate a 33x43 puzzle called output.txt into the mazes folder.

The mazerunner now accepts the name of the file as an argument so you can easily select the maze file.

### CODE REVIEW

**Comment by kishorbhat** [comment]
Thanks @JonnoFTW!

Before I merge this, could you do the following?
- update the README with instructions on generator usage, as well as the new way to run the `mazerunner.py` file (i.e., `$ python mazerunner/mazerunner.py <maze_filename>`)
- in `mazerunner.init`, handle the case where `len(sys.argv) < 2`; a lot of people don't read READMEs
- make `fname` be `sys.argv[1]` appended to "mazerunner/mazes/"; that way, users can just do
  `$ python mazerunner/mazerunner.py output.txt` instead of `$ python mazerunner/mazerunner.py mazerunner/mazes/output.txt`
- squash your commits into a single one

Otherwise, this looks good to me!

**Comment by JonnoFTW** [comment]
Okay I fixed those problems and a typo in the docs and added a thing to make the terminal sane again.

**Comment by kishorbhat** [comment]
Running the following:

``` bash
$ python3 mazerunner/generator.py output.txt 33 43
$ python mazerunner/mazerunner.py output.txt
```

gives me:

``` bash
File "mazerunner/mazerunner.py", line 107, in render
    screen.addstr('\n')
error: addstr() returned ERR
```

It runs fine if I don't specify the maze name, however.

**Comment by JonnoFTW** [comment]
Are you on windows or linux? What version of python? It worked fine for me on Linux with python 3 and 2.

**Comment by kishorbhat** [comment]
Neither; I'm on Mac. I just found it weird that the normal case works, but specifying the filename leads to errors.

Generator works as expected; only tested `mazerunner` with Python2.

I'll verify on Linux after class in a couple of hours.

**Comment by JonnoFTW** [comment]
Everything worked fine for me on Windows and Linux with python 2.7 and python 3.4

It's probably mishandling the blank last line, you can modify your code to ignore any empty lines (minus the newline). Also make sure your terminal window is big enough to fit the whole maze in.

**Comment by kishorbhat** [comment]
> Also make sure your terminal window is big enough to fit the whole maze in.

This was it. I'll add a note to README about this.

Thanks again, @JonnoFTW! This certainly makes the game more meaty. 👍

**Pull request merged**
